name: Docker

on:
  push:
    tags:
      - "docker"

env:
  APP_NAME: stat_server
  APP_VERSION: "1.0"
  DOCKERHUB_REPO: idoge/stat_server
  GIT_TAG: ""

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          # GitHub Repo => Settings => Secrets 增加 docker hub 登录密钥信息
          # DOCKERHUB_USERNAME 是 docker hub 账号名.
          # DOCKERHUB_TOKEN: docker hub => Account Setting => Security 创建.
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 通过 git 命令获取当前 tag 信息, 存入环境变量 GIT_TAG
      - name: Generate GIT TAG
        run: echo GIT_TAG=`git describe --tags --always` >> $GITHUB_ENV

      # 构建 Docker 并推送到 Docker hub
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.GIT_TAG }}
