name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-latest
    name: macos (${{ matrix.platform.target }})
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform:
          - target: "aarch64-apple-darwin"
          - target: "x86_64-apple-darwin"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Strip
        continue-on-error: true
        run: |
          strip target/${{ matrix.platform.target }}/release/stat_server
          strip target/${{ matrix.platform.target }}/release/stat_client
          cp config.toml target/${{ matrix.platform.target }}/release/
          cp systemd/stat_server.service target/${{ matrix.platform.target }}/release/
          cp systemd/stat_client.service target/${{ matrix.platform.target }}/release/

      - name: Compress binaries
        continue-on-error: true
        uses: svenstaro/upx-action@v2
        with:
          strip: false
          args: -q --best --lzma
          files: |
            target/${{ matrix.platform.target }}/release/stat_server
            target/${{ matrix.platform.target }}/release/stat_client

      - name: Zip Release - Server
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: server-${{ matrix.platform.target }}.zip
          directory: target/${{ matrix.platform.target }}/release/
          path: |
            stat_server
            config.toml

      - name: Zip Release - Client
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: client-${{ matrix.platform.target }}.zip
          directory: target/${{ matrix.platform.target }}/release/
          path: |
            stat_client

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          # 手动运行时指定一个 tag 名字，否则可能失败
          tag_name: ${{ github.ref_name }}
          files: |
            target/${{ matrix.platform.target }}/release/server-${{ matrix.platform.target }}.zip
            target/${{ matrix.platform.target }}/release/client-${{ matrix.platform.target }}.zip
          generate_release_notes: true
          draft: false

  linux:
    runs-on: ubuntu-latest
    name: linux (${{ matrix.platform.target }})
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform:
          - target: "x86_64-unknown-linux-musl"
          - target: "aarch64-unknown-linux-musl"
    container:
      image: docker://ghcr.io/rust-cross/rust-musl-cross:${{ matrix.platform.target }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Install packages
        run: |
          apt-get update -y -qq
          apt-get install zip git llvm -y -qq

      - name: Build release
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: LLVM Strip
        continue-on-error: true
        run: |
          llvm-strip target/${{ matrix.platform.target }}/release/stat_server
          llvm-strip target/${{ matrix.platform.target }}/release/stat_client
          cp config.toml target/${{ matrix.platform.target }}/release/
          cp systemd/stat_server.service target/${{ matrix.platform.target }}/release/
          cp systemd/stat_client.service target/${{ matrix.platform.target }}/release/

      - name: Zip Release - Server
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: server-${{ matrix.platform.target }}.zip
          directory: target/${{ matrix.platform.target }}/release/
          path: |
            stat_server
            stat_server.service
            config.toml

      - name: Zip Release - Client
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: client-${{ matrix.platform.target }}.zip
          directory: target/${{ matrix.platform.target }}/release/
          path: |
            stat_client
            stat_client.service

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            target/${{ matrix.platform.target }}/release/server-${{ matrix.platform.target }}.zip
            target/${{ matrix.platform.target }}/release/client-${{ matrix.platform.target }}.zip
          generate_release_notes: true
          draft: false

  windows-or-linux-others:
    name: Cross build for ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: aarch64-linux-android
            suffix: ""
            use-cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            suffix: ""
            use-cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
            use-cross: false

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Install Cross
        if: matrix.platform.use-cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build release
        run: |
          if [ "${{ matrix.platform.use-cross }}" = "true" ]; then
            cross build --release --target=${{ matrix.platform.target }}
          else
            cargo build --release --target=${{ matrix.platform.target }}
          fi
        shell: bash

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: bin-${{ matrix.platform.target }}.zip
          directory: target/${{ matrix.platform.target }}/release/
          path: |
            stat_server${{matrix.platform.suffix}}
            stat_client${{matrix.platform.suffix}}

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          tag_name: ${{ github.ref_name }}
          files: target/${{ matrix.platform.target }}/release/bin-${{ matrix.platform.target }}.zip
          generate_release_notes: true
          draft: false